version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/go/src/app
    expose:
      - "8080"
      - "40000"
    ports:
      - '8080:8080'
      - '40000:40000'
    security_opt:
      - "apparmor:unconfined"
    cap_add:
      - "SYS_PTRACE"